version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/ssl/private/:/etc/ssl/private
