version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/common.conf:/etc/nginx/common.conf
      - ./etc/nginx/common_location.conf:/etc/nginx/common_location.conf
      - ./etc/nginx/redirect.conf:/etc/nginx/redirect.conf
      - ./etc/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ./etc/ssl/private/:/etc/ssl/private
