version: '3'

services:
  reverse:
    container_name: reverse
    hostname: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/:/etc/nginx
      - ./etc/ssl/private/:/etc/ssl/private
